{{-if .Values.wazuh.deployment.enabled -}}
# Wazuh authd password secret
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-authd-pass
data:
  authd.pass: cGFzc3dvcmQ= # string "password" base64 encoded
{{- end -}}