apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
spec:
  selector:
    matchLabels:
      name: wazuh-agent
  template:
    metadata:
      labels:
        name: wazuh-agent
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      imagePullSecrets:
        - name: regcred
      containers:
        - name: wazuh-agent
          image: kajov/wazuh-agent-installer
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: W_MANAGER
              value: "{{ .Values.agent.managerURL }}"
          resources:
            limits:
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: ossec-conf
              mountPath: /var/ossec/etc/ossec.conf
              subPath: ossec.conf
            - name: wazuh-authd-pass
              mountPath: /var/ossec/etc/authd.pass
              subPath: authd.pass
              readOnly: true
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      terminationGracePeriodSeconds: 1
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: ossec-conf
          configMap:
            name: ossec-conf
        - name: wazuh-authd-pass
          secret:
            secretName: wazuh-authd-pass
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
      serviceAccount: wazuh-agent
      serviceAccountName: wazuh-agent
